//! Battlefields with nothing to argue about but skill.
//!
//! The skill-gap table needs ground where the only difference between the two
//! ends is who is commanding, so every feature is declared once and reflected
//! through the centre. That was not always true: it used to be written as rows
//! of ASCII with forest at fixed columns — symmetric *as text*, and sheared
//! into asymmetry by the odd-r offset conversion, which gave side A nine
//! forest hexes near its deployment against side B's four and cost about four
//! points of measured win rate.
//!
//! [`Arena::assert_is_mirrored`] is why that cannot come back, and it is
//! called by [`Arena::map`] itself rather than being left for a caller to
//! remember.
//!
//! # Why the ground is varied, and why that is not a contradiction
//!
//! The first version of the skill arena was grass with one belt of trees per
//! side, on the reading that ground worth *nothing* is the cleanest way to
//! isolate execution. That reading is wrong, and three separate measurements
//! said so before anybody worked out why:
//!
//! - `5 over 3` paid about 52% there, which is barely more than a coin, so the
//!   table could not tell a middling commander from a good one at all.
//! - `--sweep planner.horizon_rounds=2,4,6` came back null: a commander who
//!   plans one round ahead and one who plans eight played the same game.
//! - The road-reading terms — `route_caution`, `contest_aversion` and
//!   `difficulty_foresight` — moved the skill table by less than its own noise.
//!
//! Ground with nothing on it does not isolate skill, it **removes the thing
//! skill is for**. A commander cannot be better at reading a road on a map
//! with no roads, and she cannot be better at picking cover on a map that is
//! all one terrain; blur her judgment as hard as you like and she still ends
//! up on grass, next to grass. What an arena has to be is *symmetric*, which
//! is a completely different requirement from *featureless* — and symmetry is
//! exactly what the reflections give for free, however complicated the ground
//! gets.
//!
//! # Two reflections, not one
//!
//! Point symmetry alone is **not enough** once the ground is varied, and
//! finding that out cost a measurement. A first draft of [`SKILL_ARENA`] was
//! point-symmetric, passed the mirror assertion, and then reported side B
//! winning the equal-skill pairing 25-11 on three seeds of four (52-92 over
//! four seeds, against 73-71 on the old bare arena).
//!
//! The cause is a rule this project has already decided about. A tiebreak may
//! only read quantities a reflection preserves, and where a total order is
//! still needed for determinism the coordinate key goes last, "so the compass
//! decides only a left-or-right choice off the line of advance". Four such
//! tiebreaks exist in `ai/`. They are correct as written — *provided that a
//! left-or-right choice is worth nothing*. The moment an arena had a hill on
//! one flank and water on the other, absolute-left stopped being worth what
//! absolute-right was worth, every crew leaned the same absolute way, and the
//! two ends were no longer facing congruent ground.
//!
//! So every arena here is symmetric under **both** reflections: the point
//! reflection through the centre ([`Arena::mirror`]), which swaps the two
//! ends, and the reflection across the axis of advance ([`Arena::flip`]),
//! which swaps left and right. Every feature is declared once and gets up to
//! four images. Under the second symmetry a compass tiebreak still sends
//! everybody the same absolute way and it no longer pays anybody anything,
//! because the ground it sends them to is congruent to the ground it sends
//! them from.
//!
//! # The coordinates the symmetry is diagonal in
//!
//! Writing a doubly symmetric feature by declaring one shape and taking its
//! four images works — [`Arena::symmetric`] does exactly that, and
//! [`SKILL_ARENA`] is built that way — but it is hard to *predict*, because
//! the flip is not a sign change in either axial coordinate. Take the wood
//! declared at arena-relative `(-4, 4)` on the skill arena: its flip lands at
//! `(0, -4)`, which is not where anybody drawing on paper would have put it.
//!
//! There is a change of coordinates that makes the group trivial, and
//! [`RIDGE_ARENA`] is written in it. For a hex at arena-relative axial
//! `(x, y)`, put
//!
//! ```text
//! s = 2x + y      the along-axis coordinate, doubled
//! t = y           the lateral coordinate, off the axis of advance
//! ```
//!
//! Then `mirror` is `(s, t) -> (-s, -t)` and `flip` is `(s, t) -> (s, -t)`, so
//! the group generated by the two is exactly *"negate either coordinate"*, and
//! **a set of hexes is doubly symmetric if and only if it is described by
//! `|s|` and `|t|` alone**. [`Arena::band`] is that description: a rectangle
//! in `(|s|, |t|)` is a feature that cannot come out asymmetric, and a
//! battlefield written entirely out of bands cannot drift the way the ASCII
//! rows did.
//!
//! `s` is doubled because `s` and `t` always share a parity — `s - t = 2x` —
//! so one hex of along-axis distance is two of `s`. The hexagon of radius `R`
//! is `|t| <= R`, `|s - t| <= 2R` and `|s + t| <= 2R`.

use crate::Hex;
use crate::map::{Battlefield, MapFile};
use std::collections::HashMap;

/// One layer of terrain: the palette glyph, and every hex it covers. Layers
/// are applied in order and the later one wins, so the list is a set of small
/// claims about what stands on what.
pub type Layer = (&'static str, Vec<Hex>);

/// One piece of scoring ground: id, the name a log prints, what it pays a
/// round, and its hexes.
pub type Objective = (&'static str, &'static str, u32, Vec<Hex>);

/// One of an arena's two reflections, carrying the name a report calls it by.
///
/// A named pair rather than a bare function pointer because every caller that
/// walks both reflections also has to say *which* one it is complaining about,
/// and a check that reports "the arena is grass here and forest there" without
/// naming the reflection sends the reader hunting the wrong symmetry.
pub type Reflection = (&'static str, fn(&Arena, Hex) -> Hex);

/// Both of them, in the order every check walks them.
pub const REFLECTIONS: [Reflection; 2] = [("mirror", Arena::mirror), ("flip", Arena::flip)];

/// One measurement battlefield: the ground, the elevation, what scores, and
/// where the two forces form up.
///
/// A struct rather than a module of free functions because there are two of
/// them now and a table has to be able to name one. Everything a caller reads
/// goes through this, so `--arena` reaches the map, the deployment and the
/// symmetry checks together and there is no way to fight one arena's ground
/// with another's order of battle.
///
/// The layout arms are function pointers rather than data because a feature is
/// a *rule* — "the crest is the band within one hex of the axis and one of the
/// centre" — and writing the rule down is what keeps it symmetric. A literal
/// list of hexes would be the ASCII rows again with extra steps.
pub struct Arena {
    /// The name `--arena` takes, and the map id the battle is fought on.
    pub id: &'static str,
    /// What to call it in a table heading.
    pub name: &'static str,
    /// Radius of the hexagon, in hexes.
    pub radius: u32,
    /// Where the centre lands in map-file offset coordinates. The map is built
    /// around it, so it is the reflection pivot as well as the middle.
    pub centre: [i32; 2],
    /// Points a side has to bank to win outright.
    pub victory_score: u32,
    /// One line for a table heading: what a commander has to get right here.
    pub blurb: &'static str,
    /// Terrain, as layers applied in order — later wins. The glyphs are the
    /// palette [`Arena::map`] declares.
    layers: fn(&Arena) -> Vec<Layer>,
    /// Elevation levels, for the hexes that are not at zero.
    elevation: fn(&Arena) -> HashMap<Hex, i32>,
    /// `(id, name, value, hexes)` for each piece of scoring ground.
    objectives: fn(&Arena) -> Vec<Objective>,
    /// Where each side forms up, west first. See [`Arena::deployment`].
    deployment: fn(&Arena) -> Vec<(Hex, Hex)>,
}

/// Every arena a table can be pointed at, in the order `--arena` lists them.
pub const ARENAS: &[&Arena] = &[&SKILL_ARENA, &RIDGE_ARENA];

/// The arena every number this project has quoted was measured on, and what
/// `--arena` defaults to. Changing this is changing every past measurement's
/// meaning, which is why it is a named constant rather than `ARENAS[0]`.
pub const DEFAULT_ARENA: &Arena = &SKILL_ARENA;

/// Look an arena up by the name `--arena` takes.
pub fn arena_named(id: &str) -> Option<&'static Arena> {
    ARENAS.iter().copied().find(|a| a.id == id)
}

impl Arena {
    /// The middle, in axial coordinates.
    pub fn centre_hex(&self) -> Hex {
        crate::offset_to_hex(self.centre[0], self.centre[1])
    }

    /// The point reflection that swaps the arena's two ends.
    ///
    /// One function, used by the terrain, the elevation, the objectives, the
    /// deployment and the tests, so there is no second opinion about what "the
    /// other side" means.
    pub fn mirror(&self, h: Hex) -> Hex {
        self.centre_hex() * 2 - h
    }

    /// Reflection across the axis of advance, which swaps left and right.
    ///
    /// The axis is the line of constant `y` through the centre — the direction
    /// a side advances — and in cube coordinates the reflection fixing it is
    /// `(x, y, z) -> (-z, -y, -x)`, which in axial terms is `(x, y) -> (x + y,
    /// -y)`. It is an isometry, so a feature and its image are the same shape
    /// at the same distance from the middle, and it commutes with
    /// [`Arena::mirror`]: the two generate a four-element group and every
    /// feature has one, two or four images under it.
    pub fn flip(&self, h: Hex) -> Hex {
        let c = self.centre_hex();
        let rel = h - c;
        c + Hex::new(rel.x + rel.y, -rel.y)
    }

    /// Declare something on one side and get it on both ends.
    pub fn mirrored(&self, seeds: impl IntoIterator<Item = Hex>) -> Vec<Hex> {
        let mut out = Vec::new();
        for h in seeds {
            out.push(h);
            out.push(self.mirror(h));
        }
        out.sort_by_key(|h| (h.x, h.y));
        out.dedup();
        out
    }

    /// Declare something once and get every image of it under both reflections.
    ///
    /// The stronger twin of [`Arena::mirrored`]. See the module doc for why
    /// point symmetry alone was not enough.
    pub fn symmetric(&self, seeds: impl IntoIterator<Item = Hex>) -> Vec<Hex> {
        let mut out = Vec::new();
        for h in seeds {
            let flipped = self.flip(h);
            out.extend([h, flipped, self.mirror(h), self.mirror(flipped)]);
        }
        out.sort_by_key(|h| (h.x, h.y));
        out.dedup();
        out
    }

    /// A hex at arena-relative axial coordinates: west is `-x`, and a line of
    /// constant `y` is a straight hex line down the middle.
    pub fn rel(&self, x: i32, y: i32) -> Hex {
        self.centre_hex() + Hex::new(x, y)
    }

    /// The along-axis and lateral coordinates a doubly symmetric feature is
    /// naturally written in.
    ///
    /// See the module doc: `mirror` negates both and `flip` negates the
    /// second, so `(|s|, |t|)` is exactly a hex's orbit under the arena's
    /// symmetry group.
    pub fn axis_key(&self, h: Hex) -> (i32, i32) {
        let rel = h - self.centre_hex();
        (2 * rel.x + rel.y, rel.y)
    }

    /// Every hex of the arena whose along-axis and lateral distances fall
    /// inside the given bands — the primitive [`RIDGE_ARENA`] is built out of.
    ///
    /// Doubly symmetric by construction rather than by reflection, because
    /// `|s|` and `|t|` are precisely the quantities both reflections preserve.
    /// `s` counts *half*-hexes along the axis, so the first range is twice the
    /// along-axis reach the feature is meant to have.
    pub fn band(
        &self,
        along: std::ops::RangeInclusive<i32>,
        lateral: std::ops::RangeInclusive<i32>,
    ) -> Vec<Hex> {
        self.tiles()
            .into_iter()
            .filter(|h| {
                let (s, t) = self.axis_key(*h);
                along.contains(&s.abs()) && lateral.contains(&t.abs())
            })
            .collect()
    }

    /// Every hex on the arena, in a deterministic order.
    pub fn tiles(&self) -> Vec<Hex> {
        let mut out: Vec<Hex> = self.centre_hex().range(self.radius).collect();
        out.sort_by_key(|h| (h.x, h.y));
        out
    }

    /// Every hex within `radius` of `at`, `at` included.
    ///
    /// A disc is closed under the point reflection about its own centre, so a
    /// mirrored disc is a disc and there is no orientation to get wrong the
    /// way a text rectangle has.
    pub fn disc(&self, at: Hex, radius: u32) -> Vec<Hex> {
        at.range(radius).collect()
    }

    /// `n` hexes starting at `from` and stepping by `step`.
    pub fn line(&self, from: Hex, step: Hex, n: i32) -> Vec<Hex> {
        (0..n).map(|k| from + step * k).collect()
    }

    /// Where each side forms up, and its mirror. Side 0 takes the first of
    /// each pair.
    ///
    /// The two halves of a flip pair are **adjacent in this list**. That
    /// ordering is a contract with the caller: a battle stages the i-th
    /// vehicle of each side on the i-th pair, so entries `2k` and `2k + 1`
    /// getting the same chassis is what makes the *force* symmetric across the
    /// axis of advance as well as through the centre.
    ///
    /// It is not a nicety. A laterally symmetric battlefield with a laterally
    /// asymmetric force puts the lateral asymmetry straight back: two mediums
    /// on one flank and a tank destroyer on the other means absolute-left is
    /// worth something different to the two ends again, which is the confound
    /// the whole second reflection exists to remove.
    pub fn deployment(&self) -> Vec<(Hex, Hex)> {
        (self.deployment)(self)
    }

    /// The ground worth holding: `(id, name, value, hexes)`.
    pub fn objectives(&self) -> Vec<Objective> {
        (self.objectives)(self)
    }

    /// The map, built and checked: its ground and its scenario.
    pub fn map(&self) -> Option<Battlefield> {
        self.map_with_formations(&[])
    }

    /// The map, declaring these formations as `(id, side)`: the arena's
    /// ground with a chain of command on it, for the tables that measure
    /// what commanders do. Formations are declarations, not ground, so the
    /// mirror check is unaffected by them.
    pub fn map_with_formations(&self, formations: &[(&str, u8)]) -> Option<Battlefield> {
        let centre = self.centre_hex();
        let radius = self.radius as i32;

        let mut terrain: HashMap<Hex, char> = HashMap::new();
        for (glyph, hexes) in (self.layers)(self) {
            let ch = match glyph {
                "mud" => 'm',
                "forest" => 'f',
                "water" => 'w',
                "road" => 'R',
                "town" => 't',
                _ => unreachable!("unknown arena layer `{glyph}`"),
            };
            for hex in hexes {
                if hex.distance_to(centre) <= radius {
                    terrain.insert(hex, ch);
                }
            }
        }
        let elevation = (self.elevation)(self);

        // A bounding box on the offset grid wide enough for the hexagon. The
        // shear costs half a column per row, so the columns have to stretch by
        // the radius as well as by itself.
        let cols = 0..=self.centre[0] + radius + radius / 2 + 1;
        let mut rows: Vec<String> = Vec::new();
        let mut levels: Vec<String> = Vec::new();
        for row in 0..=self.centre[1] + radius {
            let mut terrain_row = String::new();
            let mut level_row = String::new();
            for col in cols.clone() {
                let hex = crate::offset_to_hex(col, row);
                if hex.distance_to(centre) > radius {
                    // A space is "no tile here", which is how a sparse
                    // `HexMap` spells the outside of a shape.
                    terrain_row.push(' ');
                    level_row.push(' ');
                } else {
                    terrain_row.push(*terrain.get(&hex).unwrap_or(&'g'));
                    level_row.push(match elevation.get(&hex).copied().unwrap_or(0) {
                        0 => '0',
                        1 => '1',
                        n => char::from_digit(n as u32, 10).unwrap_or('9'),
                    });
                }
            }
            rows.push(terrain_row);
            levels.push(level_row);
        }

        let objectives: Vec<serde_json::Value> = self
            .objectives()
            .into_iter()
            .map(|(id, name, value, hexes)| {
                let at: Vec<[i32; 2]> = hexes.into_iter().map(crate::hex_to_offset).collect();
                serde_json::json!({ "id": id, "name": name, "at": at, "value": value })
            })
            .collect();
        let file: MapFile = serde_json::from_value(serde_json::json!({
            "id": self.id,
            "kind": "battle",
            "shape": "free",
            "palette": {
                "g": "grass", "f": "forest", "R": "road",
                "m": "mud", "w": "water", "t": "town",
            },
            "rows": rows,
            "elevation": levels,
            "objectives": objectives,
            "victory_score": self.victory_score,
            "formations": formations
                .iter()
                .map(|(id, side)| serde_json::json!({ "id": id, "name": id, "side": side }))
                .collect::<Vec<_>>(),
        }))
        .ok()?;
        let field = Battlefield::from_map_file(&file).ok()?;
        self.assert_is_mirrored(&field);
        Some(field)
    }

    /// Refuse to hand back an arena that is not the mirror it claims to be.
    ///
    /// A runtime check rather than a test, because the thing being defended is
    /// a *claim in a table heading*: `skill gap: ... on a mirrored arena`. The
    /// first version of the skill arena was asymmetric for months — nine
    /// forest hexes within six of one deployment against four of the other —
    /// and no test failed, because there was no test, because the symmetry was
    /// believed rather than asserted. It costs about a microsecond per run of
    /// a table that fights hundreds of battles, and every number the skill-gap
    /// and brains tables print depends on it being true.
    ///
    /// It compares elevation as well as terrain. That is not hypothetical
    /// tidiness: the ground carries hills, and a hill whose mirror is half a
    /// level lower is worth a shot from one end of the map and not the other,
    /// which is the same confound as the sheared woods in a form nobody would
    /// see by reading the map.
    pub fn assert_is_mirrored(&self, field: &Battlefield) {
        let tiles: HashMap<Hex, (&str, i32)> = field
            .terrain
            .iter()
            .map(|(h, t)| (h, (t.terrain.as_str(), t.elevation)))
            .collect();
        for (name, image) in REFLECTIONS {
            for (hex, ground) in &tiles {
                let there = image(self, *hex);
                match tiles.get(&there) {
                    None => panic!("{} has {hex:?} but not its {name} {there:?}", self.id),
                    Some(other) => assert_eq!(
                        ground, other,
                        "{} is {ground:?} at {hex:?} and {other:?} at its {name} {there:?}",
                        self.id
                    ),
                }
            }
            for objective in field.scenario.objectives() {
                for hex in &objective.hexes {
                    assert!(
                        objective.hexes.contains(&image(self, *hex)),
                        "objective `{}` holds {hex:?} but not its {name}",
                        objective.id
                    );
                }
            }
        }

        let pairs = self.deployment();
        let deployment: std::collections::HashSet<Hex> =
            pairs.iter().flat_map(|(w, e)| [*w, *e]).collect();
        assert!(
            pairs.len().is_multiple_of(2),
            "the deployment must come in flip pairs, got {}",
            pairs.len()
        );
        for k in (0..pairs.len()).step_by(2) {
            assert_eq!(
                self.flip(pairs[k].0),
                pairs[k + 1].0,
                "deployment entries {k} and {} are not a flip pair, so the i-th \
                 vehicle of each side cannot be placed symmetrically about the axis",
                k + 1
            );
        }
        for (west, east) in pairs {
            assert_eq!(
                self.mirror(west),
                east,
                "the deployment pair {west:?}/{east:?} are not mirrors"
            );
            assert!(
                deployment.contains(&self.flip(west)),
                "the deployment hex {west:?} has no counterpart across the axis"
            );
            for hex in [west, east] {
                match tiles.get(&hex) {
                    None => panic!("the deployment hex {hex:?} is not on the map"),
                    // Every crew starts on the same kind of ground, and on the
                    // valley floor. A battle that begins with one vehicle in
                    // the trees or on a hill and three in the open is measuring
                    // the deployment and not the commanders, and a feature
                    // declared as a disc or a band can drift onto the forming-up
                    // ring without anybody noticing.
                    Some((terrain, level)) => {
                        assert_eq!(
                            *terrain, "grass",
                            "the deployment hex {hex:?} is `{terrain}`, not open ground"
                        );
                        assert_eq!(
                            *level, 0,
                            "the deployment hex {hex:?} stands at level {level}, not on the floor"
                        );
                    }
                }
            }
        }
    }
}

// --- the skill arena -------------------------------------------------------

/// The battlefield every number this project has quoted was measured on.
///
/// A road down the axis of advance, a village on the ground worth holding,
/// graded hills overlooking both, woods to move through unseen, soft ground
/// that makes leaving the road cost something, and water that has to be gone
/// around. Radius 10, 331 tiles.
///
/// **Where the hills go is not decoration, and the first draft got it
/// backwards.** Four hills flanking the village put the objective in a hollow
/// overlooked from both ends, which prices holding the ground *below* sitting
/// on the ground above it — so both sides settle on their own ridge and shoot,
/// which is the stalemate objectives were introduced to end. Measured: it took
/// `5 over 1` from 61.5% on the bare arena to 53.9%, because a commander who
/// drives to the objective is punished for it and skill mostly consists of
/// driving to the objective. Putting the crest *under* the objective says the
/// opposite and the right thing: the best firing position on the battlefield
/// and the ground that scores are the same hexes.
///
/// **Two objectives, because one is a funnel, and the funnel showed up in the
/// control row.** With a single seven-hex objective every vehicle on the field
/// converges on the same ground, and at difficulty 5 — where the blur is zero
/// and both sides therefore make identical decisions in mirrored situations —
/// the first crew to reach it is decided by movement resolution order, which
/// walks units in id order and hands side A every race. That is not a coin
/// flip that averages out: it is the same tiebreak in the same direction every
/// battle, so the equal-skill pairing read 34-110 rather than anything near
/// level, and an instrument whose control is degenerate cannot be read.
pub static SKILL_ARENA: Arena = Arena {
    id: "skill_arena",
    name: "the skill arena",
    radius: 10,
    centre: [15, 10],
    victory_score: 30,
    blurb: "a road, a hilltop village and woods on the flanks",
    layers: |a| {
        // The order is a set of small claims about the ground: soft going is
        // underneath everything because it is what the open ground *is* rather
        // than something on it; trees stand on it; water cuts through trees;
        // the road is cut through all of it, because a road through a wood is
        // a road; and the village is built where the roads meet.
        vec![
            // Soft going short of the village: no cover, twice the cost to
            // cross. This is what makes the road mean something — without it
            // the open ground beside the road is as quick as the road, so
            // there is no route decision to read and `route_caution` has
            // nothing to trade against.
            ("mud", a.symmetric(a.disc(a.rel(-4, 1), 2))),
            // The timber: a wood on each flank of each end. Cover 30 and
            // concealment 25 at double the movement cost — the covered
            // approach, slower than the road and worth taking anyway.
            ("forest", a.symmetric(a.disc(a.rel(-4, 4), 2))),
            // Water: short reaches that nothing on this battlefield can cross.
            // Small on purpose. It exists so that the crow flight and the road
            // disagree, which is the whole of what `difficulty_foresight`
            // blends between; a barrier large enough to split the arena would
            // stop the battle from happening at all.
            (
                "water",
                a.symmetric(a.line(a.rel(-5, 2), Hex::new(0, 1), 3)),
            ),
            // The road, the whole length of the axis of advance. Fixed by both
            // reflections, being the axis itself. It is the fast lane — every
            // movement class pays 1 — and also the most exposed ground on the
            // map, which is the entire point.
            ("road", a.line(a.rel(-9, 0), Hex::new(1, 0), 19)),
            // The village: the centre hex and its six neighbours. Town is
            // cover 40 against the grass's nothing, so holding the objective
            // is also *fighting from* the objective.
            ("town", a.disc(a.centre_hex(), 1)),
        ]
    },
    // A graded knoll centred on the village: crest at level 2 under the
    // objective itself, a level-1 skirt around it, level 0 beyond. The grading
    // is not decoration — every vehicle in the base mod has `max_climb: 1`, so
    // a level-2 crest with level-0 ground against it would be an objective
    // nothing can drive onto.
    elevation: |a| {
        let centre = a.centre_hex();
        a.disc(centre, 2)
            .into_iter()
            .map(|hex| (hex, if hex.distance_to(centre) <= 1 { 2 } else { 1 }))
            .collect()
    },
    objectives: |a| {
        vec![
            ("village", "The Village", 2, a.disc(a.centre_hex(), 1)),
            // `symmetric` folds these two into each other: a hex whose axis
            // projection is zero has its point reflection and its lateral
            // reflection at the same place, so the pair is the whole set.
            ("copses", "The Copses", 2, a.symmetric([a.rel(-2, 4)])),
        ]
    },
    // Six hexes on the radius-7 ring, in three flip pairs.
    deployment: |a| {
        [a.rel(-7, 1), a.rel(-7, 3), a.rel(-7, 5)]
            .into_iter()
            .flat_map(|h| [h, a.flip(h)])
            .map(|w| (w, a.mirror(w)))
            .collect()
    },
};

// --- the ridge arena -------------------------------------------------------

/// Ground a commander can be *wrong* on: a bare crest, bare spurs, and dead
/// ground behind every one of them.
///
/// Phase 2 made the evaluator price a tile by what a found gun could put on
/// her standing there, and the skill table moved by three points — the right
/// sign and not decisive. The diagnosis was that the skill arena is a radius-10
/// hexagon with two objectives and has very little for a commander who now
/// prices cover *under a specific gun* to be better at: its wood is a wood
/// wherever the enemy happens to be, and its hill is a hill. This arena is
/// built out of the distinctions the new arithmetic can see and the old one
/// could not.
///
/// Radius 12, 469 tiles, and every feature is an [`Arena::band`], so the double
/// symmetry is structural rather than asserted after the fact.
///
/// # The shape
///
/// A road down the axis of advance, over a level-2 knoll in the middle. Open
/// valley floor either side of it. A level-2 ridge along each flank, seven to
/// eight hexes off the axis, stopping ten hexes short of each end so that
/// there is a gap beside each forming-up line. Woods on the valley floor
/// inside the ridges, and more woods on the far side of them. Mud in the two
/// gaps, so that turning out through one costs a round.
///
/// # What a good commander does here that a bad one does not
///
/// **She takes the military crest, not the topographic one.** This is the
/// sharpest thing on the map and it is a choice *within a single objective*.
/// The Crest is thirteen hexes of level-2 grass, and what they can see differs
/// by a factor of two: the hex in the middle sees 68 tiles of the map and the
/// hexes at either rim see 148, because the ray from a 22.5 m eye to a 2 m
/// hull is already below 20 m one step out and the plateau blocks its own
/// middle. `candidates` offers all thirteen and `score_tile` has to pick; a
/// crew that stops on the summit has taken the objective and given up the
/// ground. The spurs say the same thing more quietly — inner edge 112 tiles,
/// outer edge 88.
///
/// **She picks the wood the enemy's gun cannot see into.** There are two kinds
/// here and they are worth completely different things:
///
/// - the *near woods*, on the valley floor inside the ridges. The crest rim
///   sees straight into them at four and six hexes, and so does the inner edge
///   of the near flank ridge. Cover 30 takes half the accuracy off a shot; it
///   does not take the shot away.
/// - the *reverse-slope woods*, beyond the ridges, which are blocked from the
///   crest, from the valley and from both edges of the ridge above them. A
///   crew there sees nine tiles and is seen by no gun that has not crossed the
///   ridge first.
///
/// A flat cover prior prices those two the same. `battle::danger::incoming`
/// does not.
///
/// **She stops on the reverse slope.** The knoll is a level-1 shoulder with a
/// level-2 crest on it, and the two shoulders cannot see each other — 20 m of
/// hill between a 12.5 m eye and a 12 m hull blocks the ray. So a crew can
/// close to within three hexes of the objective and still be in dead ground
/// from everything beyond it. The same fact cuts the map in half lengthwise:
/// a gun on the east rim cannot see the west near woods at all, so each side's
/// approach is covered from the *far* rim rather than the near one, and the
/// prize for winning the race to the crest is being able to shoot at the
/// loser's approach march.
///
/// **She takes the long way when the short way is covered.** The ridges stop
/// at `|s| <= 10`, which leaves an open gap at each end beside the forming-up
/// line. A force can turn out through it, drive the length of the far flank in
/// dead ground and come at a spur or the crest from the outside. It costs: the
/// turn crosses mud at twice the going rate, and the route is three rounds
/// against the direct two — inside `planner.horizon_rounds` of 4, which is
/// what makes it something the road-reading chooser can weigh rather than
/// ground it cannot see.
///
/// # The two objectives are different in kind
///
/// **The Crest** (13 hexes, worth 3) is the level-2 plateau in the middle: the
/// best observation on the map, no cover at all, and the road runs over it.
///
/// **The Spurs** (10 hexes, worth 2) are the level-2 tops of the two flank
/// ridges, equidistant from both ends. They are one objective holding both
/// flanks, so a side that splits to take one of each ends up contesting rather
/// than holding — a decision about where to weight a force rather than a race
/// down a funnel, which is the lesson [`SKILL_ARENA`] paid for.
///
/// Everything commanding here is bare, and everything covered here is blind.
/// That is the arena's argument in one line, and it is not a design conceit:
/// it falls out of `vision_block`, which puts a wooded neighbour 20 m above
/// the ray at your own level. A commander who understands it fights from the
/// rim and hides in the trees; one who does not sits in a wood with a good
/// gun and never fires it.
///
/// Nothing here is worth anything to one end that it is not worth to the
/// other: `|s|` and `|t|` see to that.
pub static RIDGE_ARENA: Arena = Arena {
    id: "ridge_arena",
    name: "the ridge arena",
    radius: 12,
    centre: [18, 12],
    // Five points a round if a side holds everything, against the skill
    // arena's four. Forty rather than thirty so that a battle decided on the
    // ground still has to be held for eight rounds after it is won, which is
    // long enough for the loser's counterattack to be a thing that happens.
    victory_score: 40,
    blurb: "a bare crest, bare flank ridges, and woods in the dead ground",
    layers: |a| {
        vec![
            // Soft going on the outward turn. This is the price of the covered
            // route: a force that swings wide to reach the far flank pays two
            // movement points a hex for three or four hexes, which is most of
            // a round, and that is what makes the decision cost something
            // rather than being free.
            ("mud", a.band(13..=24, 6..=7)),
            // The near woods: cover in the middle of the killing ground, in
            // full view of the crest and of both flank ridges.
            ("forest", a.band(6..=12, 4..=5)),
            // The reverse-slope woods: cover in the dead ground beyond the
            // ridges, which nothing that has not crossed a ridge can see into.
            ("forest", a.band(0..=10, 10..=11)),
            // The road down the axis of advance, stopping two hexes short of
            // the rim at each end so that it is a lane through the battlefield
            // rather than a lane off it.
            ("road", a.band(0..=20, 0..=0)),
        ]
    },
    elevation: |a| {
        let mut out: HashMap<Hex, i32> = HashMap::new();
        // The shoulders first, then the crests over the top of them, so that
        // every level-2 hex has a level-1 neighbour and `max_climb: 1` can get
        // a tank up there. Each shoulder is the *minimum* that does it — the
        // crest reaches `|s| <= 4, |t| <= 1` and a neighbour of it is at most
        // `|s| = 6, |t| = 2` — because a wider one blinds the hill it belongs
        // to: from a 22.5 m eye to a 2 m hull the ray is under 10 m for the
        // last two fifths of its length, so a level-1 lip that far out hides
        // the ground just beyond it. A first draft with the shoulder at
        // `|t| <= 3` put the near woods in dead ground from the crest, which
        // is the opposite of what they are for.
        for hex in a.band(0..=6, 0..=2) {
            out.insert(hex, 1);
        }
        for hex in a.band(0..=12, 6..=9) {
            out.insert(hex, 1);
        }
        for hex in a.band(0..=4, 0..=1) {
            out.insert(hex, 2);
        }
        for hex in a.band(0..=10, 7..=8) {
            out.insert(hex, 2);
        }
        out
    },
    objectives: |a| {
        vec![
            ("crest", "The Crest", 3, a.band(0..=4, 0..=1)),
            ("spurs", "The Spurs", 2, a.band(0..=2, 7..=8)),
        ]
    },
    // Six hexes on the radius-9 ring, in three flip pairs, clear of the mud,
    // of the near woods and of every slope.
    deployment: |a| {
        [a.rel(-9, 1), a.rel(-9, 3), a.rel(-9, 5)]
            .into_iter()
            .flat_map(|h| [h, a.flip(h)])
            .map(|w| (w, a.mirror(w)))
            .collect()
    },
};
